---
- name: tweak grub settings
  lineinfile:
    dest: /etc/default/grub
    regexp: GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
  register: grubbed
  become: yes

- name: apply changed grub settings
  command: update-grub
  become: yes
  when: grubbed | changed
  
- name: reboot
  command: shutdown -r now "Ansible updated grub"
  async: 0
  poll: 0
  become: yes
  ignore_errors: true
  when: grubbed | changed

- name: wait for server to relaunch
  local_action: wait_for host={{ inventory_hostname }} state=started
  when: grubbed | changed

- include_tasks: docker.yml

- name: pull tmpnb service images
  command: docker pull {{ item }}
  with_items:
  - jupyterhub/configurable-http-proxy
  - jupyter/tmpnb
  become: yes

- name: pull docker image for user containers
  command: docker pull {{ tmpnb_image }}
  become: yes


- name: iptables configuration
  command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8000
  become: yes

- name: configproxy
  docker_container:
    state: started
    pull: true
    image: jupyterhub/configurable-http-proxy
    network_mode: host
    name: configproxy
    restart_policy: always
    env:
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
    command: >
      --default-target http://127.0.0.1:9999
      --ip="{{ notebook_host }}"
      --api-ip="127.0.0.1"

- name: tmpnb
  docker_container:
    state: started
    pull: true
    image: jupyter/tmpnb
    network_mode: host
    name: tmpnb
    restart_policy: always
    env:
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
    volumes: /var/run/docker.sock:/docker.sock
    command: >
      python orchestrate.py
      --pool_size={{ tmpnb_pool_size }}
      --cull_timeout={{ tmpnb_cull_timeout }}
      --cull_period={{ tmpnb_cull_period }}
      --image={{ tmpnb_image }}
      --docker_version={{ tmpnb_docker_version }}
      --redirect_uri={{ tmpnb_redirect_uri }}
      --command='{{ tmpnb_command }}'
      --max_dock_workers={{ tmpnb_max_dock_workers }}
      --mem-limit={{ tmpnb_mem_limit }}
      --cpu-shares={{ tmpnb_cpu_shares }}
      --cpu-quota={{ tmpnb_cpu_quota }}
      --ip="127.0.0.1"
      --allow-origin='*'
      --allow-methods='GET, PUT, POST, PATCH, DELETE, OPTIONS'
      --allow-headers='Content-Type'
