---
- name: see if HTTPS transport is already present
  stat: path=/usr/lib/apt/methods/https get_md5=false
  register: https_transport_file

- name: ensure HTTPS transport is available to apt
  apt: update_cache=yes cache_valid_time=3600 name=apt-transport-https
  become: yes
  when: not https_transport_file.stat.exists

- name: ensure the docker apt key is trusted
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  become: yes

- name: ensure the docker apt repository is present
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main
    state: present
  become: yes
  notify: update apt

- name: install docker
  apt: update_cache=yes cache_valid_time=3600 name=docker-engine=17.05.0~ce-0~ubuntu-{{ ansible_distribution_release }}
  become: yes

- name: python
  apt: name=python state=latest
  become: yes

- name: pip install script
  get_url: dest=/tmp/get_pip.py url=https://bootstrap.pypa.io/get-pip.py

- name: pip
  command: python /tmp/get_pip.py creates=/usr/local/bin/pip
  become: yes

- name: docker-py
  # FIXME: can't upgrade to docker-py 1.10 until ansible 2.2
  pip: name=docker-py version=1.10.*
  become: yes
